### ISSUE TITLE
How Can I use your code for button drag n drop on a panel

### ISSUE THREAD

**Issue by alexlizama1** [awaescher/FluentDragDrop#13]
trying to used your package to drag and drop buttons on a panel without overstepping borders.  I can see on how to move images and listview items but buttons or other controls?
 Please help

**Comment by awaescher** [comment]
Sorry I did not understand that.

**Comment by alexlizama1** [comment]
So I need to move buttons on a panel. Have freedom to move them around in a panel. I see that you can move images from one picturebox to another. All I need is to move a button from within a panel.

Can you code do that?

Thanks
Alex

**Comment by awaescher** [comment]
You need to move controls in runtime? There are plenty solutions for this, but this is not drag and drop. So no.

You might want to look on StackOverflow.
