### ISSUE TITLE
how to let me drop object to the not predecided control

### ISSUE THREAD

**Issue by masterchen** [awaescher/FluentDragDrop#20]
This Dragdrop is awesome.
In my case , i want to drop one usercontrol to other control , now i can drog and move one control , but the target object can't not be decided , i may drop to A  or B  or C , can you give some hint how to do ? thank you very much !

**Comment by awaescher** [comment]
You can implement the DragEnter and DragDrop events in your target controls events like shown in TestForm.cs
See tab "compatibility"

**Comment by masterchen** [comment]
Thanks for your reply.

now i just make a list<> , add controls to the list, then pass the list as target.  and also i can get the drop event of  target controls,  but i want pass some argument to target , i dont know how todo .


My code like this:

source event:
`
  void Wave_MouseDown(object sender, MouseEventArgs e)
        {
            var moveVave = (WaveCtrl)sender;
            var waveList = new List<WaveCtrl>();
            /*allwaves is also a list which has many wave elements*/
            waveList.Addd(allWaves[0]);   
            waveList.Add(allWaves[1]);
            waveList.Add(allWaves[2]);
            moveVave.InitializeDragAndDrop()
                .Move()
                .Immediately()
                .WithData(moveVave.ClientID)
                .WithPreview().RelativeToCursor()
                 /*i want to pass value "ClientID"  of Wave  to target wave, i don't know it si oK or not.*/
                .To(waveList, (target,ClientID) => target.ClientID = ClientID); 

}
`

 with target contorl :

       `  wave.DragDrop += Wave_DragDrop;

      private void Wave_DragDrop(object sender, DragEventArgs e)
        {
            MessageBox.Show(((WaveCtrl)sender).SectionID.ToString() + e.Data);
        }

`
